package org.lcb.model;

import java.util.Date;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_resource.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_resource.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_resource.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_resource.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_resource.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_resource.structure
     *
     * @mbggenerated
     */
    private String structure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_resource.sort_no
     *
     * @mbggenerated
     */
    private Integer sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_resource.module_flag
     *
     * @mbggenerated
     */
    private String moduleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_resource.create_person
     *
     * @mbggenerated
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_resource.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_resource.update_person
     *
     * @mbggenerated
     */
    private String updatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_resource.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_resource.id
     *
     * @return the value of p_resource.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_resource.id
     *
     * @param id the value for p_resource.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_resource.name
     *
     * @return the value of p_resource.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_resource.name
     *
     * @param name the value for p_resource.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_resource.url
     *
     * @return the value of p_resource.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_resource.url
     *
     * @param url the value for p_resource.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_resource.remark
     *
     * @return the value of p_resource.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_resource.remark
     *
     * @param remark the value for p_resource.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_resource.parent_id
     *
     * @return the value of p_resource.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_resource.parent_id
     *
     * @param parentId the value for p_resource.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_resource.structure
     *
     * @return the value of p_resource.structure
     *
     * @mbggenerated
     */
    public String getStructure() {
        return structure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_resource.structure
     *
     * @param structure the value for p_resource.structure
     *
     * @mbggenerated
     */
    public void setStructure(String structure) {
        this.structure = structure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_resource.sort_no
     *
     * @return the value of p_resource.sort_no
     *
     * @mbggenerated
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_resource.sort_no
     *
     * @param sortNo the value for p_resource.sort_no
     *
     * @mbggenerated
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_resource.module_flag
     *
     * @return the value of p_resource.module_flag
     *
     * @mbggenerated
     */
    public String getModuleFlag() {
        return moduleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_resource.module_flag
     *
     * @param moduleFlag the value for p_resource.module_flag
     *
     * @mbggenerated
     */
    public void setModuleFlag(String moduleFlag) {
        this.moduleFlag = moduleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_resource.create_person
     *
     * @return the value of p_resource.create_person
     *
     * @mbggenerated
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_resource.create_person
     *
     * @param createPerson the value for p_resource.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_resource.create_date
     *
     * @return the value of p_resource.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_resource.create_date
     *
     * @param createDate the value for p_resource.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_resource.update_person
     *
     * @return the value of p_resource.update_person
     *
     * @mbggenerated
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_resource.update_person
     *
     * @param updatePerson the value for p_resource.update_person
     *
     * @mbggenerated
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_resource.update_date
     *
     * @return the value of p_resource.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_resource.update_date
     *
     * @param updateDate the value for p_resource.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}