package org.lcb.model;

public class RoleModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role_module.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role_module.module_id
     *
     * @mbggenerated
     */
    private Integer moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role_module.role_id
     *
     * @return the value of p_role_module.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role_module.role_id
     *
     * @param roleId the value for p_role_module.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role_module.module_id
     *
     * @return the value of p_role_module.module_id
     *
     * @mbggenerated
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role_module.module_id
     *
     * @param moduleId the value for p_role_module.module_id
     *
     * @mbggenerated
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }
}