package org.lcb.model;

public class RoleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role_resource.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role_resource.resource_id
     *
     * @mbggenerated
     */
    private Integer resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role_resource.role_id
     *
     * @return the value of p_role_resource.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role_resource.role_id
     *
     * @param roleId the value for p_role_resource.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role_resource.resource_id
     *
     * @return the value of p_role_resource.resource_id
     *
     * @mbggenerated
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role_resource.resource_id
     *
     * @param resourceId the value for p_role_resource.resource_id
     *
     * @mbggenerated
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }
}