package org.lcb.dao;

import org.lcb.model.RoleResource;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_role_resource
     *
     * @mbggenerated
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_role_resource
     *
     * @mbggenerated
     */
    int insertSelective(RoleResource record);
}