package org.lcb.dao;

import org.lcb.model.RoleModule;

public interface RoleModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_role_module
     *
     * @mbggenerated
     */
    int insert(RoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_role_module
     *
     * @mbggenerated
     */
    int insertSelective(RoleModule record);
}